// AUTO-GENERATED by scripts/generate-image-manifest.mjs — do not edit by hand.
export type MediaImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const media = {
  gallery: [
    {
      src: "/media/gallery/20220305_202442.jpg",
      width: 1000,
      height: 750,
      blurDataURL:
        "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAwAA4BaJbACdAD0Op7FuwAA/vfPkH7G1OhO+kaFaMypZD+ri065dzGisvzKMxkBwjq6PLIbPEXIY7k9oAAAAAA=",
    },
    {
      src: "/media/gallery/20220305_202559.jpg",
      width: 703,
      height: 654,
      blurDataURL:
        "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQAA8AA4BaJZwAD42Q5e+OghFiH7AA/t2cjYFvoTbQ+612gsPez16jkDEkc8Y9IOscm9fakweQa64xRUqqXhG/NbpNdpTeQM3+Q8ag40zv6wnIvm+u3aqI0bLkHllT3Sue43j46BAAAA==",
    },
    {
      src: "/media/gallery/img-20220223-wa0037--1-.jpg",
      width: 1000,
      height: 742,
      blurDataURL:
        "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAwAA4BaJZgCdAEO0vYeZJAA/vbJQvzOxR/QWQ7i+oIGoSXXY/voQK75MJbhjZpVqnmeEvBtff4ISQ5Sr2vg6HXQAA==",
    },
    {
      src: "/media/gallery/img_4969.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJQBWD+ACdhCOGjOAAP7hv/d++OsNBiP9mEeHz3YOt7QDBuqisldjUkAci0e4xv9tcaUXHsQSTlQ/yqZJiKt/9gan4BpQR38pI3mUzAAAAA==",
    },
    {
      src: "/media/gallery/img_4986.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAgCdASoQAAsAA4BaJQBOgMX1qPTNZ5n6PgAA+OXp7UUSjKHqePzcjAQQTtPbWRcNwjd7g15H4AjD2aVmRZstjd37Ek0EmGV7ALLn2KdF14mQFvcneHX5JObkPzG3ZrIvsO2OiPszbhBgAAA=",
    },
    {
      src: "/media/gallery/img_4988.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJYwCw7EejROaOhTgAP7okgXTaIQnrFiDkP7EUF2J2HynzHkaZhsckMlqgcHEjGlMxnWvkZ1ICvUbG9pjdRgZVQkhtmNwAAA=",
    },
    {
      src: "/media/gallery/img_5012.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsAA4BaJYwCsB2gAjsQ5PMW84AA/uYiEWsjzhVMMvWOWufM6b0cY+NjQHGecCWH/VAGKtXEyQmuQc4kmVIC09DC3CH27jbShqYR3WmY9oAA",
    },
    {
      src: "/media/gallery/img_5222.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAsAA4BaJZgCdAYuvkovyFloAAD+xfzEX5/WNL7NYIv2LTqtI/wcebrsXz0KkrcClysijPNHsTjYLdGSt8RSIyiEzc6fAXEV5xUIFsQAAA==",
    },
    {
      src: "/media/gallery/img_5224.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAA4BaJaACdAEetu6g86+eAAD8cxmhXH7zqsm36jFpTp+n7hOU+3AeoHpoAPNbthCi2XcHO/YJictG7P5d7YYqkzVQr9AAAz9rF8eHAAAA",
    },
    {
      src: "/media/gallery/img_5226.jpg",
      width: 1000,
      height: 668,
      blurDataURL:
        "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoQAAsAA4BaJYwCdEf/gei6AGevQAD+sQuKfWocE8JZxodjZqHz9e9iWhDfJ0Swu9rUe2qnlc0//m5HKRROeM/AIAA=",
    },
    {
      src: "/media/gallery/img_5227.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAsAA4BaJQBOkCYjEzvuHLzUgAD+m2Z6Iy0QLAwPJ+zje8yhHeYGlsm0ndOTLlzyUHG3oO20c6ewh+S8YIfRw5EtkLezwJIjzOgpC7buCGsAAAA=",
    },
    {
      src: "/media/gallery/img_5228.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAsAA4BaJagCdH8AgqzBTOE1JUAA/nk7eI+UQ9MrbHtnwM4zvsxFQfDqVAKNd2kds1V8nU3vqrMaxZR7jgjTybCsW1sJQzMOENqFpwskJcR1FQAAAA==",
    },
    {
      src: "/media/gallery/img_5230.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAsAA4BaJbACdACZup0AAMn+9NJ6RrwjNmpa8IttH8dmJw0sSVJFRqOScFd1ztUBDj6xSEoYZ1Xn80uSOAGUU6v5394orgAAAA==",
    },
    {
      src: "/media/gallery/img_5231.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQAAsAA4BaJbACdH8Agsi7PXoPewAA+T/qTdbbqovbI2B37yJfsX1PeaisV8SmYbC2KqGS4O+3/Ueu0E7WDnKa5x+h0oK/3UR6pBpLgkE6Wr/DkgjonWSziEfqXg/NgPPC/gCb5EuAAA==",
    },
    {
      src: "/media/gallery/img_5232.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA4BaJagCdADbm824GEEAAP5mWqRYtj95x/7CtIXO9PvR4v3KjwyHC8VRhaICtQXZ+Q/350LMbP6Ff/Z2773Ib7IvOZJQsbwcVD+dS8cExp6r9Vs2fd8htJRzDQb/CeAAAAA=",
    },
    {
      src: "/media/gallery/img_5233.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJaACdAEXzQsKavtYAPzXlX1qeUo/nTfVF6Bpa4Ly29mMaaIWlEvr2VC4r66jYZ4KRPMwW5/oXm4WVP31JnH3NuluuM9g9ohOgWzdUNeWX3A1z3AAAA==",
    },
    {
      src: "/media/gallery/img_5236.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJbACdADPvjLS+k0gAPfPLUg5OK7nszwvIkfdmqOBexxf6vQsQ18WZ8lgJHUsfyQvQowfoUtp1nqMPSpTuZFbm37T+xBs4F1lKDBXE1iLo+L+AAA=",
    },
    {
      src: "/media/gallery/img_5237.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQAAHwAWSDPOLK4abAAD+miTO2ezV8i8XX/OL9xoD4y29JI4x8BFeS2tK2IXL6KQ/NpHuUsfD2AEpVOW73holPkjN9PH90yvNlj8RMflgekuEjm1VKL4xYLTHmTpbgttBYQu4+eobfUBUgizRJRn8HD4sP59wAAA=",
    },
    {
      src: "/media/gallery/img_5238.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJZgCsADDmR0hGAQAAPt8EsH33lh0mTV83sUubBRYpgfmukTX1sgHPNHqJF1cNpBQkKhLhF5iIWQ09GcZmtrRykknSXKAegAAAA==",
    },
    {
      src: "/media/gallery/img_5239.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JYwCsABg2ox5zrzhAoAD7ZPytsHtEpkvywszRwzd8IQDHD6kyhBAfKk+f6klT0ulxoPvGAQyowRh1XmdlxuNuLAGvtD04c2RgAA==",
    },
    {
      src: "/media/gallery/img_5240.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJYgCdAEP/iyN+oQAAP7zU4i6GwuUZ46IjjcqSr07Dhvef/9Vr3ukKzVzytxERqMxcEhJMoKSWEJ+Ho0lbXdIdpJf6gHcX/YQqxRF/p7HcoFhxIAAAA==",
    },
    {
      src: "/media/gallery/img_5241.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBgfeAAr5DBKl0dPTRpO4AD8igel7576qrTc9oG4J+TFhn84dL10zyHUudh9WtxMqBSi1UE3ylx9ygdfx0z/F8zYXijDif8yfZ7Sq93Xvel/UpJZMHYKLGfei/XRc96FfZivSAcNl3qyAP8Bhe7xtPha9pimcwj3HOQYMRNFTubZOgIc+wrz8nAYAA==",
    },
    {
      src: "/media/gallery/img_5243.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAsAA4BaJYwCdAEPBez4Pm5kAP3HxAofl7g74K4k+Xp+VSu4scWeqkoO4wy4h7c25kKlznCNDZZI9dqJBptiyAA=",
    },
    {
      src: "/media/gallery/img_5244.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA4BaJQBOgB9lTVEH70QA/oPgf6T2NvGVw8uvcmdY0DIa9YjHUQAX7exlOV9ZHAX+Vfn/+nL+roP9YO3IjizBAAAA",
    },
    {
      src: "/media/gallery/img_5245.jpg",
      width: 1000,
      height: 672,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJQBOgMXSiNYS2MwAAM4m4rIi/AHVidsEeS7+95nCYGg+fTWTeXnNttNZxPIHyN/uxRMKxiwYHsPcD/uFn8tua9AAAA==",
    },
    {
      src: "/media/gallery/img_5246.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJQBOgCB/lBVCzK+AAP0p/TGV75g4ztKAWx/atjbJZN0sjDpbwFNj0gorvaOhm4QPN5csbdBhmKasQQRW+DgI14AAAA==",
    },
    {
      src: "/media/gallery/img_5248.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJYgCdAEWNj2iVgAA+U1mn4D4wEQ3AbjnNzM+yxIOLUZA2eRlUwockpKX1QWdizjJ40EQ8/JnJfnza2E5eAGUCZbyj1LcaYarK8Fa6qAAAA==",
    },
    {
      src: "/media/gallery/img_5252.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JagCdAB7AksK8de9I1zDA2QAA/F1fzWOAgZYw4J4oyElVsJCdvLHpiRHhDjP+pId0FaeCRbPI9A54GKJGjtw1wo0xPcREYysMx4naFri0eu6EV/16A6Ieqpi2Sl9r0jQF/AAA",
    },
    {
      src: "/media/gallery/img_5253.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJZgCdH8AF6cc3EqAAP6RRL3gBEDKRujM/VF6Q1N5abXOwwGqg/4QkiLs8uI8FlqX0exc7tec73Nv4ECt/QuhEzKzUXO+qzTUKMgqyvbEk1x1TLAAAA==",
    },
    {
      src: "/media/gallery/img_5255.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJQBOgBbKP38p4EAA/sdlR+aB4HAbK+KTWIlzwycfcEAvTvul0Z1jJrSygOFbTS4FQy5WKXcwPiWk5ztEqPbBXoYJ6IjiqKEiooEk9vAAAA==",
    },
    {
      src: "/media/gallery/img_5256.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAsAA4BaJYwCdAChwZIgAAD+7/PK9Sqxux6Rny7lqGm4dHD9lKAoX0E0sJndg5DYZ2bwD5SRw0/yljzza4EiTiMkj6gL7jdgAA==",
    },
    {
      src: "/media/gallery/img_5257.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJYwCdAEQEsYkTbc0AP6YTM12g0+5xg5MTWetUQx/SpTaNBV2wSle6Mv9dD4hSOS7tvT1+nZuZraxmX9BJaSz1C5vAAAA",
    },
    {
      src: "/media/gallery/img_5258.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAsAA4BaJQBOgMW54HfbezY3SoAA/pgnaPbmZX5ezoM32CqCSbHPL3ZDdPMh8rUrKBky03UyHKDQOuOoh8PEJmweGMcZr5HZ5lv1fIYGrHAECAAAAA==",
    },
    {
      src: "/media/gallery/img_5259.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsAA4BaJYgC7AEXTvoUnmwAAP61H3YEAkotTlGI1mDsA5m13etfuW1YZAqQw909i3vco8syseuJhEbDLMBoCRQAAA==",
    },
    {
      src: "/media/gallery/img_5260.jpg",
      width: 1000,
      height: 666,
      blurDataURL:
        "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAsAA4BaJbAC7AC2cFPIQAD+VHhXpBMMwnslQfa/wRZfQwK4qwHD+IkC/2uvRO/XA/98u7TtzOKPnw2tODHAAAA=",
    },
    {
      src: "/media/gallery/img_5261.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJaACdADMIyjtWQAA/rP5ketGhCrO84WJBpobPUMjZG5JCwdh80AgiBchFxHmd/2qFJzyCk1Wp8ON6jSFpHiMGJlfQAAA",
    },
    {
      src: "/media/gallery/img_5262.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAsAA4BaJQBOgBwsy0pYAAD+4aRg4LxY+G/EIPnwubTHTQ6KX0nFz5o2VwdxU0EaBb+Apd0cnMQRGw4onHBbRg4sS2IAAAA=",
    },
    {
      src: "/media/gallery/img_5263.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA4BaJbACdADjbM6V7EwAAP7EIJmQY9wSwDjdJ/m8v6VEyG94GnHJ3FryErz4mNrxJFjrleon2ZFUa/+mDW7vjik5GCxFwattW1iLJcwAAAA=",
    },
    {
      src: "/media/gallery/img_5265.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsAA4BaJbACdAEWgGzOhzb8SwAA/idfefBC6+Ahss7BfLXDjZzjytzk6FEKx99CUcT8i8im+JMbDc039MRJH2zRnKOb1lgw3VHpGi5YwAAA",
    },
    {
      src: "/media/gallery/img_5266.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJbACdAD6Ii7Kq+CwAPlWDoebLjMxWwPybkWKb42s6UnMzARZrvLy28G8z83zCn/uq8Axh9xzVLluyVLf2AAA",
    },
    {
      src: "/media/gallery/img_5267.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABgAPu1yrU+pp6QiMAgBMB2JQBbZBEPZ+4j4e/s9NGAA/rgSkRc4OqAUVz9LgZof3QJnJJCqs1NFH4bBLVi2Ug3TSVoDJxLgJXbAyOwYzZ00XPHQp9H+Z3sQpnyGTpdXHfzriKaneT0YvJWuAA==",
    },
    {
      src: "/media/gallery/img_5268.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAwCdASoQABgAPu1iqk4ppaQiMAgBMB2JYwCdAA/HidmDcaAA/pMzS8atjXk6OO6gn/NdVxmbngeP80651HJgZ5uLIIV2c8P3TOTq1pFJ+bDcLuzRBxjcKVYpIvf+IZm3zKLgzAAAAA==",
    },
    {
      src: "/media/gallery/img_5269.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoQABgAPu1iqk4ppaQiMAgBMB2JZwDE2B9EN1w3ZTBoAAD+w/myRp5NjqB5ar3UUQmh8Vt5btUiUzFF9I+GhJPBT5Oi9KYAAAA=",
    },
    {
      src: "/media/gallery/img_5270.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JYwAAXBvOyhN0MTZ87GHAAP3fn3eBYAGicR8hQd+Kib/w0/qG0cahdnLiRWfbfPzTU8rSY5vYmTHLj9K8+bT8IRndhoVEb4QsfnZtNoOFjt7BJQ/tGK6SAAA=",
    },
    {
      src: "/media/gallery/img_5271.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAA4BaJaACdAEN67OTLj2CAAD+mcD0t6hhsd5PElGsfH9secZpBRUkHQhYuTuSSOlVjXtx+1P/ZfX0NfDz4g76ZW0Ezp2zV1iZ3HzsMAAA",
    },
    {
      src: "/media/gallery/img_5273.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJagCdADdpzF5ttIAAP7TW//2AiMAG87yCwDxQ7tJd0HCMIV/PF/o8a1v5Rk+zUutDcZL+J4qjqvFD5SvZTq2gp1ksl/Rr4AAAA==",
    },
    {
      src: "/media/gallery/img_5275hdr.jpg",
      width: 1000,
      height: 666,
      blurDataURL:
        "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAsAA4BaJbACdAYt9axinLPx7AAA870ewIEXpQipK+M1F7hUrYLMOowHdUJO11DxbrYnBvo1XC22Wd097uPMt5qqYkQeeAWxJiY5OpMe3zHRS05pfH2/urtgwAAA",
    },
    {
      src: "/media/gallery/img_5276.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABgAPu1iqk2ppaQiMAgBMB2JaACdACB/zpcVST+k77RlS17QAP7ER3qkuhtsp85sljY/+N3mWPCb6kvhZWWzc/VeQbxKhPTjNXzO6OBLxJMRqVzXhXzp5FaaEDrGt0UEln0+nf1FXEuMu72v/8jr4rHw1X0+fdTxVLZEDLQnbgGO62cPtAAA",
    },
    {
      src: "/media/gallery/img_5278.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAsAA4BaJbACdAC3QHtKAAD91ML9M5A2E8O6NLKYuCSRMgpTcwIMWpQ6WaejB8d8mC93dBlFiS+LyLhTQAfw73Zm5dbNfN0QAAAA",
    },
    {
      src: "/media/gallery/img_5280.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZgCdMoR8eB6iYASKMNnWbpGkmAD6PcdZz/sU/djNXpH9a/r3FkD+VxQV4n52d4dsZaHB3rzOizYCcAinFYzd0LLPp8uD40DUHGEicCQsg884bNNMYTUKVPY8TWMpcK/PjiLfQomrce8C9ez2shOayzkfIYlivvpVvRH8F5ml/2PhSBX8gaAA",
    },
    {
      src: "/media/gallery/img_5282.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAsAA4BaJbACdADIgg3QAP6POUmZfIKj0p1pYCnBiehFkg+ERQLil653zDnFC8HApGB4SUQGgd03z803c/inro4873bJCEUAAA==",
    },
    {
      src: "/media/gallery/img_5283.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoADD88uvGEd6J56c5bLwAD7kmVyny4pygPPLB+b8nSoQahiLhRLbtn6HL8ThsS4eM4r8BOZEdIANIrndtTT/49s6Bn/Er8gflaXl/xnYpUachI5RPf29HDprkhZnk4JLGHyyCTpDmRq/t04AAA=",
    },
    {
      src: "/media/gallery/img_5285.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JaACw7Buoef6VuPGGNslYAPFALZ3tbtQKwK8mZ/adnDQZYoQBX+vRa0oTwTWnI2ivn3Q8zb/jilWI7taxegUBGgf8ECJXmnJSbFo0AAA=",
    },
    {
      src: "/media/gallery/img_5286.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JQBOmUABRrR6bzIlyIUgDAAD+xyM+mXE+3ZmnNtELH9lv1Qbv0g/8x9ljCTLJYuhNhrm+iogHAS8MtdRCGDQ7tlLZF5fzwUS+nC5rd3GAHk+bnBzQEqrx9nDci/sifzWDIym4Ewxv0OJYQOckYjmMkpgAAA==",
    },
    {
      src: "/media/gallery/img_5287.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJZACdAB7DFZAAPlmoQk2Evk7hpdAX83EYKPmLWeNAvk0i2SHaUYVrE9B3Pz13KReI1AdlIauNlWsBe33TBnnhvEOrvIAAAA=",
    },
    {
      src: "/media/gallery/img_5288.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdL1yBnVfl+jIWmmDkusAAAPwNOuxGgmSVaJ+kLgm18fWdVHnMyFCpI9dgkd/deAd5aqdtsa5qCzhVLaT3AYffEbMq1KHBdMNTHVMjGr/C6efdDQ7PUAsZXg63CAJNu4Ti7vZ8SfrnP43EfkgU5JKSnpPwUUgiQLfo+MXDY0iSPgA=",
    },
    {
      src: "/media/gallery/img_5289.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBYdsYYVXG3ywKm7VgYO5cZUAAD8JUMUqdq9llgVVOVR97rB2fdk7StwtnOYz67eoIjzs1jpa7oS4SJpQv8Jzl96RFLmbs20pX8dFydOvb0TsKfByax9OVLxnHRJ9qcQ/OO0wLhF54LohQ5SIDOzPd/DckABD056Xhu1CELvS1f/YNqQrxl78AA=",
    },
  ],
  new: [
    {
      src: "/media/new/img_5053.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAsAA4BaJQBOgB6JddjVkccQAP7wSZiIVtPZXlC1avNlw3kvx76KMNxv5StuT5xfbDGZRENs/wPSPchyUF6/oyDcMZH8uFEmIp2/MGQwAAAA",
    },
    {
      src: "/media/new/img_5055.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA4BaJYgCdAD1PeWIlb4AAPqb2VBZJCGGt6iiu4BRaheiX4PftKLs8Vj0x9DISNHWSLqqogapv7QjtkkossHk5EtJOJ8AAA==",
    },
    {
      src: "/media/new/img_5056.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAsAA4BaJZgCdADMkg9P/9wAAP6JhltJmwksQ7E+SIRHa9zDD3iS2xsm/9zdqrgTcThpnJRVIl+bvjzJL587ga2EjeiHTBn/lJqmPqhtgAAA",
    },
    {
      src: "/media/new/img_5057.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJbACdACHrW9AAPfRlwCUAnXMYAJxkv5uN0Vqnh7OvCzolzLfP30fe09e89/yp4vSpDWM8AIG7jGs1KMjqTHtaOqCguwAAAA=",
    },
    {
      src: "/media/new/img_5059.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAsAA4BaJZgCdAYvrdVeylCTSAAA/meFb82FfAfYBXEYjTG2yvoG47hWWUM+btI+WY1D6MZd2s9369UoNWJvn6Jk/fDTWPe2HwWY7Morl/EAAAA=",
    },
    {
      src: "/media/new/img_5061.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAsAA4BaJYwCdAEPh3TcdbPZWAD+6Kat+SzzVbYPmb4IHosRSxDuRmAHULl8UZuGAqcrhcfjUQlNoWWEWNHz6MABlvHlgDmqQAAA",
    },
    {
      src: "/media/new/img_5062.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJbACdAEO5Erx7cSEAPltotWgWoROQQed15dm/SfrGKW7I00L1LUbXXcb/r1hWTfEn3cAgB4gMJ7VbsDvE/yssa2AKCg0AAA=",
    },
    {
      src: "/media/new/img_5065.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoQAAsAA4BaJYgCdAYsj21FPupCAAD+8XK3a64urh9h6t1Z3lp26A5UjWd0Q/qK8jcxmTSL4Jb4jUEMThAn91snKoSyIjvbE1PzbFqlbgjvYe7zMumJYAwwEtVOQhBgOEeQAAAA",
    },
    {
      src: "/media/new/img_5066.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAsAA4BaJYgCdAD6fKvV0CjIAAD2Q7L1iudO9vKFDdp6nltV2Ffc4zkih7G6rJLmrOkbcd7BtprFxBCYAr/LFO1tdmlq/G5K2pXVYqXAAA==",
    },
    {
      src: "/media/new/pano-outside.jpg",
      width: 1200,
      height: 364,
      blurDataURL:
        "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQAAUAA4BaJbACdAD1PA5z4AD+Tj3uLHUMmjSlmjRFGkY1F6J1GVBN0z4Ym+dcsPfXvrq8AAA=",
    },
  ],
  hero: [
    {
      src: "/media/hero/antet.jpg",
      width: 1920,
      height: 600,
      blurDataURL:
        "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAUAA4BaJYwCdAD2JS9zgAD7+vIEdBAUaQNhahoo5VDnaVneTY0vvxOqt1CJ+3uETwAA",
    },
    {
      src: "/media/hero/pano.jpg",
      width: 1920,
      height: 779,
      blurDataURL:
        "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAYAA4BaJQBOgCIHAtwuKAAA/sYHoARuOuIzW80ReTSn8Rd1EEJmr5F5DuRclSNX+QAA",
    },
  ],
  "units/city": [
    {
      src: "/media/units/city/img_4969.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJQBWD+ACdhCOGjOAAP7hv/d++OsNBiP9mEeHz3YOt7QDBuqisldjUkAci0e4xv9tcaUXHsQSTlQ/yqZJiKt/9gan4BpQR38pI3mUzAAAAA==",
    },
    {
      src: "/media/units/city/img_5228.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAsAA4BaJagCdH8AgqzBTOE1JUAA/nk7eI+UQ9MrbHtnwM4zvsxFQfDqVAKNd2kds1V8nU3vqrMaxZR7jgjTybCsW1sJQzMOENqFpwskJcR1FQAAAA==",
    },
    {
      src: "/media/units/city/img_5230.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAsAA4BaJbACdACZup0AAMn+9NJ6RrwjNmpa8IttH8dmJw0sSVJFRqOScFd1ztUBDj6xSEoYZ1Xn80uSOAGUU6v5394orgAAAA==",
    },
    {
      src: "/media/units/city/img_5231.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQAAsAA4BaJbACdH8Agsi7PXoPewAA+T/qTdbbqovbI2B37yJfsX1PeaisV8SmYbC2KqGS4O+3/Ueu0E7WDnKa5x+h0oK/3UR6pBpLgkE6Wr/DkgjonWSziEfqXg/NgPPC/gCb5EuAAA==",
    },
    {
      src: "/media/units/city/img_5233.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJaACdAEXzQsKavtYAPzXlX1qeUo/nTfVF6Bpa4Ly29mMaaIWlEvr2VC4r66jYZ4KRPMwW5/oXm4WVP31JnH3NuluuM9g9ohOgWzdUNeWX3A1z3AAAA==",
    },
    {
      src: "/media/units/city/img_5237.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQAAHwAWSDPOLK4abAAD+miTO2ezV8i8XX/OL9xoD4y29JI4x8BFeS2tK2IXL6KQ/NpHuUsfD2AEpVOW73holPkjN9PH90yvNlj8RMflgekuEjm1VKL4xYLTHmTpbgttBYQu4+eobfUBUgizRJRn8HD4sP59wAAA=",
    },
    {
      src: "/media/units/city/img_5238.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJZgCsADDmR0hGAQAAPt8EsH33lh0mTV83sUubBRYpgfmukTX1sgHPNHqJF1cNpBQkKhLhF5iIWQ09GcZmtrRykknSXKAegAAAA==",
    },
    {
      src: "/media/units/city/img_5248.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJYgCdAEWNj2iVgAA+U1mn4D4wEQ3AbjnNzM+yxIOLUZA2eRlUwockpKX1QWdizjJ40EQ8/JnJfnza2E5eAGUCZbyj1LcaYarK8Fa6qAAAA==",
    },
  ],
  "units/travel": [
    {
      src: "/media/units/travel/img_5252.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JagCdAB7AksK8de9I1zDA2QAA/F1fzWOAgZYw4J4oyElVsJCdvLHpiRHhDjP+pId0FaeCRbPI9A54GKJGjtw1wo0xPcREYysMx4naFri0eu6EV/16A6Ieqpi2Sl9r0jQF/AAA",
    },
    {
      src: "/media/units/travel/img_5255.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJQBOgBbKP38p4EAA/sdlR+aB4HAbK+KTWIlzwycfcEAvTvul0Z1jJrSygOFbTS4FQy5WKXcwPiWk5ztEqPbBXoYJ6IjiqKEiooEk9vAAAA==",
    },
    {
      src: "/media/units/travel/img_5259.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsAA4BaJYgC7AEXTvoUnmwAAP61H3YEAkotTlGI1mDsA5m13etfuW1YZAqQw909i3vco8syseuJhEbDLMBoCRQAAA==",
    },
    {
      src: "/media/units/travel/img_5261.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJaACdADMIyjtWQAA/rP5ketGhCrO84WJBpobPUMjZG5JCwdh80AgiBchFxHmd/2qFJzyCk1Wp8ON6jSFpHiMGJlfQAAA",
    },
    {
      src: "/media/units/travel/img_5262.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAsAA4BaJQBOgBwsy0pYAAD+4aRg4LxY+G/EIPnwubTHTQ6KX0nFz5o2VwdxU0EaBb+Apd0cnMQRGw4onHBbRg4sS2IAAAA=",
    },
    {
      src: "/media/units/travel/img_5265.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsAA4BaJbACdAEWgGzOhzb8SwAA/idfefBC6+Ahss7BfLXDjZzjytzk6FEKx99CUcT8i8im+JMbDc039MRJH2zRnKOb1lgw3VHpGi5YwAAA",
    },
    {
      src: "/media/units/travel/img_5267.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABgAPu1yrU+pp6QiMAgBMB2JQBbZBEPZ+4j4e/s9NGAA/rgSkRc4OqAUVz9LgZof3QJnJJCqs1NFH4bBLVi2Ug3TSVoDJxLgJXbAyOwYzZ00XPHQp9H+Z3sQpnyGTpdXHfzriKaneT0YvJWuAA==",
    },
    {
      src: "/media/units/travel/img_5270.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JYwAAXBvOyhN0MTZ87GHAAP3fn3eBYAGicR8hQd+Kib/w0/qG0cahdnLiRWfbfPzTU8rSY5vYmTHLj9K8+bT8IRndhoVEb4QsfnZtNoOFjt7BJQ/tGK6SAAA=",
    },
  ],
  "units/tango": [
    {
      src: "/media/units/tango/img_5271.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAA4BaJaACdAEN67OTLj2CAAD+mcD0t6hhsd5PElGsfH9secZpBRUkHQhYuTuSSOlVjXtx+1P/ZfX0NfDz4g76ZW0Ezp2zV1iZ3HzsMAAA",
    },
    {
      src: "/media/units/tango/img_5275hdr.jpg",
      width: 1000,
      height: 666,
      blurDataURL:
        "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAsAA4BaJbACdAYt9axinLPx7AAA870ewIEXpQipK+M1F7hUrYLMOowHdUJO11DxbrYnBvo1XC22Wd097uPMt5qqYkQeeAWxJiY5OpMe3zHRS05pfH2/urtgwAAA",
    },
    {
      src: "/media/units/tango/img_5276.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABgAPu1iqk2ppaQiMAgBMB2JaACdACB/zpcVST+k77RlS17QAP7ER3qkuhtsp85sljY/+N3mWPCb6kvhZWWzc/VeQbxKhPTjNXzO6OBLxJMRqVzXhXzp5FaaEDrGt0UEln0+nf1FXEuMu72v/8jr4rHw1X0+fdTxVLZEDLQnbgGO62cPtAAA",
    },
    {
      src: "/media/units/tango/img_5278.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAsAA4BaJbACdAC3QHtKAAD91ML9M5A2E8O6NLKYuCSRMgpTcwIMWpQ6WaejB8d8mC93dBlFiS+LyLhTQAfw73Zm5dbNfN0QAAAA",
    },
    {
      src: "/media/units/tango/img_5282.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAsAA4BaJbACdADIgg3QAP6POUmZfIKj0p1pYCnBiehFkg+ERQLil653zDnFC8HApGB4SUQGgd03z803c/inro4873bJCEUAAA==",
    },
    {
      src: "/media/units/tango/img_5285.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JaACw7Buoef6VuPGGNslYAPFALZ3tbtQKwK8mZ/adnDQZYoQBX+vRa0oTwTWnI2ivn3Q8zb/jilWI7taxegUBGgf8ECJXmnJSbFo0AAA=",
    },
    {
      src: "/media/units/tango/img_5287.jpg",
      width: 1000,
      height: 667,
      blurDataURL:
        "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJZACdAB7DFZAAPlmoQk2Evk7hpdAX83EYKPmLWeNAvk0i2SHaUYVrE9B3Pz13KReI1AdlIauNlWsBe33TBnnhvEOrvIAAAA=",
    },
    {
      src: "/media/units/tango/img_5288.jpg",
      width: 667,
      height: 1000,
      blurDataURL:
        "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdL1yBnVfl+jIWmmDkusAAAPwNOuxGgmSVaJ+kLgm18fWdVHnMyFCpI9dgkd/deAd5aqdtsa5qCzhVLaT3AYffEbMq1KHBdMNTHVMjGr/C6efdDQ7PUAsZXg63CAJNu4Ti7vZ8SfrnP43EfkgU5JKSnpPwUUgiQLfo+MXDY0iSPgA=",
    },
  ],
  "units/cover": [
    {
      src: "/media/units/cover/city.jpg",
      width: 600,
      height: 400,
      blurDataURL:
        "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAsAA4BaJaACdH8AGEnM0e3GwAD+eTt4j5YH1A0X0pHgtUhUVPMRIrcK6WyHJGbEvPfrW9LAA6SDCIq3RwMUEWvboSOItLnKGTwVX1BCNtyoAAA=",
    },
    {
      src: "/media/units/cover/tango.jpg",
      width: 600,
      height: 400,
      blurDataURL:
        "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJaACdAEVVhBhAoAA/tOip7GWDPc3BZi9nsr/jcQ/brEjsVaqLJ/g0uRNkgEcef0yZppG+WUPs5GB6Dmsamcxnzx/V4ID7JrCxSwqTEAAAA==",
    },
    {
      src: "/media/units/cover/travel.jpg",
      width: 600,
      height: 400,
      blurDataURL:
        "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAsAA4BaJaACdAEf1qLwjur0cAD+s/pk+TT1txbZ7LTMB3cvWtY1OO6vuDP5vvKT4VFPN/YOEqbp+RvcV7BGeEwdPndBsciAAA==",
    },
  ],
} as const satisfies Record<string, readonly MediaImage[]>;

export type MediaKey = keyof typeof media;
